### ISSUE TITLE
Breaks due to internal refactoring

### ISSUE THREAD

**Issue by samth** [AlexKnauth/typed-racket-stream#1]
@andmkent has just landed some internal refactoring that breaks this code. You can fix it to use the new names (see racket/typed-racket#349) or use `parse-type` to produce types using the public type syntax, instead of constructing them explicitly, which is what I'd recommend.

**Comment by AlexKnauth** [comment]
Or I could use `unsafe-require/typed`, right?

**Comment by samth** [comment]
I don't think that will work for your use case [here](https://github.com/AlexKnauth/typed-racket-stream/blob/master/typed/racket/stream/stream-pred.rkt) because you're giving a type to `stream?`, but maybe you can make it work.

**Comment by AlexKnauth** [comment]
This should work, right?

``` racket
#lang typed/racket/base

(provide stream?)

(require typed/racket/unsafe)
(unsafe-require/typed racket/stream
                      [stream? (-> Any Boolean : #:+ (Sequenceof Any))])
```

**Comment by AlexKnauth** [comment]
In my test file DrRacket's background expansion is giving me this error with that:

```
test-stream.rkt:18:15: Type Checker: missing type for identifier; consider using `require/typed' to import it identifier: stream? from module: typed/racket/stream in: stream?
  #(368 7)
```

Although when I run it it works. (Edit: never mind, deleting the `compiled/` directories fixed it)

**Comment by AlexKnauth** [comment]
Thanks!
