### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/typed-racket-stream#3]
Contributor @bennn, I would like to add the MIT License to this repository.

If you agree, please post a message saying so, e.g. — "I hereby license my contributions to `typed-racket-stream` under the MIT license."

**Comment by bennn** [comment]
I agree. I hereby license my contributions to typed-racket-stream under the MIT license.

**Comment by AlexKnauth** [comment]
Added in https://github.com/AlexKnauth/typed-racket-stream/commit/4f49db416dd2267af94c3f63d27f27101f9771ee
